<?php
namespace Evance\Resource;

use Evance\AbstractResource;
use Evance\ApiClient;
use Webmozart\Assert\Assert;

class Locations extends AbstractResource
{
    public function __construct(ApiClient $client)
    {
        parent::__construct($client);
    }

    /**
     * @param $id
     * @return array
     */
    public function getOne(int $id)
    {
        Assert::integerish($id, __METHOD__ . ' expects an $id as an integer');
        return $this->call('GET', "/".$this->version."locations/{$id}.json");
    }

    /**
     * @param array $params
     * @return mixed
     */
    public function getMany(array $params = [])
    {
        Assert::isArray($params, __METHOD__ . ' expects $query to be supplied as an array of key value pairs');
        return $this->call('GET', "/".$this->version."locations.json", [], $params);
    }

    public function postOne(array $body)
    {
        parent::postOne($body); // TODO: Change the autogenerated stub
    }

    public function putOne(int $id, array $body)
    {
        parent::putOne($id, $body); // TODO: Change the autogenerated stub
    }

    public function deleteOne(int $id)
    {
        parent::deleteOne($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return array
     * @deprecated use getMany()
     */
    public function get($id)
    {
        return $this->getOne($id);
    }

    /**
     * @param $params
     * @return mixed
     * @deprecated use getMany()
     */
    public function search($params = [])
    {
        return $this->getMany($params);
    }
}
